#! /bin/bash

/etc/init.d/rstudio-server start
export RUNNING=1

stop_rstudio()
{
    /etc/init.d/rstudio-server stop
    [ -e "/home/rstudio/.rstudio/session-persistent-state" ] && rm /home/rstudio/.rstudio/session-persistent-state
    export RUNNING=0
}

trap stop_rstudio SIGINT SIGTERM

while [ "$RUNNING" == "1" ]
do
    sleep 1
done

rm /home/rstudio/.rstudio/session-persistent-state
