#!/bin/bash

echo requires docker 17.05.0 or greater

export VERSION=${1-latest}
echo build using rocker/rstudio:${VERSION}
echo creating labkey/rstudio:${VERSION}
docker build --build-arg VERSION=${VERSION} -t labkey/rstudio-base:${VERSION} .
