FROM public.ecr.aws/lambda/python:3.9

RUN python3 -m pip install --upgrade pip
COPY requirements.txt  .
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
RUN pip3 install jupyterlab

COPY Intro.ipynb ${LAMBDA_TASK_ROOT}

COPY app.py ${LAMBDA_TASK_ROOT}

CMD [ "app.handler" ] 
