#!/bin/bash

echo requires docker 17.05.0 or greater

export VERSION=${1-3.4.2}
shift

echo creating labkey/rsandbox:${VERSION}
docker build $* --build-arg VERSION=${VERSION} -t labkey/rsandbox:${VERSION} .
