#!/bin/bash

echo requires docker 17.05.0 or greater

export VERSION=${1-3.4.2}
shift

echo build VERSION=${VERSION}
pushd ../rstudio-base
./make $VERSION $*
popd
docker build $* --build-arg VERSION=${VERSION} -t labkey/rstudio:$VERSION .
